# [IPS]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [IPS]    Script Date: 17/11/2020 12:08:31 a. m. ******/
CREATE DATABASE [IPS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IPS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\IPS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IPS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\IPS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [IPS] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IPS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IPS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IPS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IPS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IPS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IPS] SET ARITHABORT OFF 
GO
ALTER DATABASE [IPS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [IPS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IPS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IPS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IPS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IPS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IPS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IPS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IPS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IPS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [IPS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IPS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IPS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [IPS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [IPS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IPS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [IPS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [IPS] SET RECOVERY FULL 
GO
ALTER DATABASE [IPS] SET  MULTI_USER 
GO
ALTER DATABASE [IPS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IPS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [IPS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [IPS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [IPS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [IPS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'IPS', N'ON'
GO
ALTER DATABASE [IPS] SET QUERY_STORE = OFF
GO

# [dbo].[Cita]

In [0]:
USE [IPS]
GO

In [0]:
/****** Object:  Table [dbo].[Cita]    Script Date: 17/11/2020 12:08:31 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cita](
	[IdentificacionMedico] [varchar](20) NOT NULL,
	[IdentificacionPaciente] [varchar](20) NOT NULL,
	[FechaCita] [datetime] NOT NULL,
	[verificada] [bit] NULL,
	[Especialidad] [varchar](20) NULL,
 CONSTRAINT [PK_Cita_1] PRIMARY KEY CLUSTERED 
(
	[IdentificacionMedico] ASC,
	[IdentificacionPaciente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Medico]

In [0]:
/****** Object:  Table [dbo].[Medico]    Script Date: 17/11/2020 12:08:31 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medico](
	[IdentificacionMedico] [varchar](20) NOT NULL,
	[Nombres] [nvarchar](50) NOT NULL,
	[Apellidos] [nvarchar](50) NOT NULL,
	[Especialidad] [nvarchar](50) NOT NULL,
	[SalarioPorCita] [int] NOT NULL,
	[AñosExperiencia] [int] NOT NULL,
	[numeroTotalCumplidas] [int] NULL,
 CONSTRAINT [PK_Medico] PRIMARY KEY CLUSTERED 
(
	[IdentificacionMedico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Paciente]

In [0]:
/****** Object:  Table [dbo].[Paciente]    Script Date: 17/11/2020 12:08:31 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Paciente](
	[IdentificacionPaciente] [varchar](20) NOT NULL,
	[Nombres] [nvarchar](50) NOT NULL,
	[Apellidos] [nvarchar](50) NOT NULL,
	[FechaNacimiento] [datetime] NOT NULL,
	[Direccion] [nvarchar](50) NOT NULL,
	[Telefono] [varchar](20) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[FechaRegistro] [datetime] NOT NULL,
	[Multas] [int] NOT NULL,
 CONSTRAINT [PK_Paciente] PRIMARY KEY CLUSTERED 
(
	[IdentificacionPaciente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Usuario_IPS]

In [0]:
/****** Object:  Table [dbo].[Usuario_IPS]    Script Date: 17/11/2020 12:08:31 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario_IPS](
	[Usuario] [nvarchar](30) NULL,
	[Contraseña] [nvarchar](20) NULL
) ON [PRIMARY]
GO

# [dbo].[Cita]

In [0]:
INSERT [dbo].[Cita] ([IdentificacionMedico], [IdentificacionPaciente], [FechaCita], [verificada], [Especialidad]) VALUES (N'465453', N'1036669712', CAST(N'2020-10-15T00:00:00.000' AS DateTime), 0, N'Optometria')
INSERT [dbo].[Cita] ([IdentificacionMedico], [IdentificacionPaciente], [FechaCita], [verificada], [Especialidad]) VALUES (N'5453', N'1036669712', CAST(N'2020-11-13T00:00:00.000' AS DateTime), 0, N'Medico General')
INSERT [dbo].[Cita] ([IdentificacionMedico], [IdentificacionPaciente], [FechaCita], [verificada], [Especialidad]) VALUES (N'5453', N'1111', CAST(N'2020-05-15T00:00:00.000' AS DateTime), 0, N'Medico General')
INSERT [dbo].[Cita] ([IdentificacionMedico], [IdentificacionPaciente], [FechaCita], [verificada], [Especialidad]) VALUES (N'745452', N'1111', CAST(N'2025-12-02T00:00:00.000' AS DateTime), NULL, N'Optometria')
GO

# [dbo].[Medico]

In [0]:
INSERT [dbo].[Medico] ([IdentificacionMedico], [Nombres], [Apellidos], [Especialidad], [SalarioPorCita], [AñosExperiencia], [numeroTotalCumplidas]) VALUES (N'465453', N'Roberto', N'dsgdf', N'Optometria', 4000000, 100, NULL)
INSERT [dbo].[Medico] ([IdentificacionMedico], [Nombres], [Apellidos], [Especialidad], [SalarioPorCita], [AñosExperiencia], [numeroTotalCumplidas]) VALUES (N'5453', N'fghfh', N'gfjgf', N'Medico General', 25000, 3, NULL)
INSERT [dbo].[Medico] ([IdentificacionMedico], [Nombres], [Apellidos], [Especialidad], [SalarioPorCita], [AñosExperiencia], [numeroTotalCumplidas]) VALUES (N'745452', N'gfhfgh', N'ghjgh', N'Optometria', 566546, 5, NULL)
GO

# [dbo].[Paciente]

In [0]:
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'', N'', N'', CAST(N'2020-10-11T00:00:00.000' AS DateTime), N'poblado', N'2569991', N'prueba@gmail.com', CAST(N'2020-10-11T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'0', N'0', N'0', CAST(N'2020-02-11T00:00:00.000' AS DateTime), N'0', N'0', N'0', CAST(N'2020-09-11T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'100', N'Santiago', N'Gómez', CAST(N'1905-06-01T00:00:00.000' AS DateTime), N'calle 80', N'5085005', N'santigm1905@gmail.com', CAST(N'1905-06-27T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'1000539471', N'Santiago ', N'Gómez Montoya', CAST(N'1900-01-01T00:00:00.000' AS DateTime), N'Manrique', N'3114814936', N'santigm1905@gmail.com', CAST(N'1900-01-01T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'1036669712', N'Diego Alejandro ', N'Durango Garro', CAST(N'1900-01-01T00:00:00.000' AS DateTime), N'belén', N'3008883769', N'lejodurango@gmail.com', CAST(N'1900-01-01T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'111', N'1', N'1', CAST(N'2020-09-11T00:00:00.000' AS DateTime), N'1', N'1', N'1', CAST(N'2020-09-11T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'1111', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), N'romboy', N'3145609', N'asdg7@gmail.com', CAST(N'1900-01-01T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'121', N'dsf', N'fsdf', CAST(N'1900-01-01T00:00:00.000' AS DateTime), N'sfsfsf', N'121', N'sfsdf', CAST(N'1900-01-01T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'213554', N'bhjkjhv', N'fgjfgjfgj', CAST(N'1900-01-01T00:00:00.000' AS DateTime), N'fjgjfg', N'5452452', N'dfhfdhfd', CAST(N'1900-01-01T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'22', N'11', N'11', CAST(N'2020-09-11T00:00:00.000' AS DateTime), N'', N'', N'', CAST(N'2020-09-11T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'42420', N'ghffh', N'fghfd', CAST(N'2020-11-11T00:00:00.000' AS DateTime), N'895dhfgh98q', N'89844', N'ghdghgfh', CAST(N'2020-11-11T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'4563542452', N'hhhh', N'fghghgfh', CAST(N'2020-10-11T00:00:00.000' AS DateTime), N'hgfghgh', N'1515', N'f6h46fg4h', CAST(N'2020-10-11T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'5', N'11', N'11', CAST(N'2020-09-11T00:00:00.000' AS DateTime), N'11', N'11', N'1', CAST(N'2020-09-11T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'555', N'', N'', CAST(N'2020-10-11T00:00:00.000' AS DateTime), N'454ghjngh', N'4545', N'454544564', CAST(N'2020-10-11T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'85486465', N'fhf', N'dfhdfh', CAST(N'2020-11-11T00:00:00.000' AS DateTime), N'fh654fdh564', N'561654', N'564hfghq@..', CAST(N'2020-11-11T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'9696', N'Santiago', N'Gómez', CAST(N'1905-06-01T00:00:00.000' AS DateTime), N'calle 80', N'5085005', N'santigm1905@gmail.com', CAST(N'1905-06-27T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'96968585', N'Santiago', N'Gómez', CAST(N'1905-06-01T00:00:00.000' AS DateTime), N'calle 80', N'5085005', N'santigm1905@gmail.com', CAST(N'1905-06-27T00:00:00.000' AS DateTime), 0)
INSERT [dbo].[Paciente] ([IdentificacionPaciente], [Nombres], [Apellidos], [FechaNacimiento], [Direccion], [Telefono], [Email], [FechaRegistro], [Multas]) VALUES (N'9856465464', N'ElGa', N'rrote', CAST(N'1900-01-01T00:00:00.000' AS DateTime), N'fgdfgdg', N'54645454', N'ElGarrote@gmail.com', CAST(N'1900-01-01T00:00:00.000' AS DateTime), 0)
GO

# [dbo].[Usuario_IPS]

In [0]:
INSERT [dbo].[Usuario_IPS] ([Usuario], [Contraseña]) VALUES (N'AlejandroDurango', N'123456789*')
INSERT [dbo].[Usuario_IPS] ([Usuario], [Contraseña]) VALUES (N'SantiagoGomez', N'1905+')
INSERT [dbo].[Usuario_IPS] ([Usuario], [Contraseña]) VALUES (N'ProfeEdisson', N'0000')
INSERT [dbo].[Usuario_IPS] ([Usuario], [Contraseña]) VALUES (N'0', N'0')
INSERT [dbo].[Usuario_IPS] ([Usuario], [Contraseña]) VALUES (NULL, N'')
GO

# [IPS]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [IPS] SET  READ_WRITE 
GO